FROM node:alpine

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
RUN SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install --registry=https://registry.npm.taobao.org

COPY ./ /app
RUN npm run build

ENTRYPOINT [ "node", "server.js" ]
